import { motion } from 'framer-motion';
import { FileText, ChevronRight } from 'lucide-react';
import { Link } from 'react-router-dom';

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: [
      'By accessing or using Taurus AI\'s platform and services, you agree to be bound by these Terms and Conditions.',
      'If you do not agree to these terms, please discontinue use of our services immediately.',
      'We reserve the right to modify these terms at any time, with notice provided via email or in-app notification.',
    ],
  },
  {
    title: '2. Description of Services',
    content: [
      'Taurus AI provides AI-powered recruitment solutions including resume screening, video interviewing, phone screening, coding assessments, MCQ tests, and system design evaluations.',
      'Services are provided on a credit-based subscription model as detailed in our Pricing page.',
      'We reserve the right to modify, suspend, or discontinue any part of our services at any time.',
    ],
  },
  {
    title: '3. Acceptable Use',
    content: [
      'You agree to use Taurus AI services only for lawful purposes and in accordance with these Terms.',
      'You must not use our services to discriminate against candidates based on protected characteristics.',
      'You must not attempt to reverse-engineer, decompile, or extract our AI algorithms or proprietary technology.',
      'You must not share your account credentials with unauthorized parties.',
      'Automated scraping or data harvesting from our platform is strictly prohibited.',
    ],
  },
  {
    title: '4. Intellectual Property',
    content: [
      'All content, features, and functionality of the Taurus AI platform are owned by Taurus, Inc. and are protected by intellectual property laws.',
      'You are granted a limited, non-exclusive, non-transferable license to use our services for your internal business purposes.',
      'Candidate reports and assessments generated by our AI are provided for your use under the subscription terms.',
      'You may not reproduce, distribute, or create derivative works from our platform content.',
    ],
  },
  {
    title: '5. Data and Privacy',
    content: [
      'Your use of our services is also governed by our Privacy Policy, which is incorporated into these Terms by reference.',
      'You are responsible for obtaining proper consents from candidates before using our AI tools to evaluate them.',
      'You must ensure compliance with applicable employment and data protection laws in your jurisdiction.',
    ],
  },
  {
    title: '6. Payment and Billing',
    content: [
      'Subscription fees are billed in advance on a monthly or annual basis as selected.',
      'Credits purchased are non-refundable unless required by applicable law.',
      'We reserve the right to change pricing with 30 days written notice.',
      'Late payments may result in service suspension after a 7-day grace period.',
    ],
  },
  {
    title: '7. Limitation of Liability',
    content: [
      'Taurus AI\'s total liability for any claims arising from these Terms shall not exceed the amount paid by you in the 12 months preceding the claim.',
      'We are not liable for indirect, incidental, special, or consequential damages of any kind.',
      'We do not guarantee specific hiring outcomes or candidate quality resulting from use of our services.',
    ],
  },
  {
    title: '8. Termination',
    content: [
      'Either party may terminate the agreement with 30 days written notice.',
      'We may immediately terminate or suspend access for material breach of these Terms.',
      'Upon termination, your right to use the services ceases and unused credits are forfeited.',
      'Data deletion will occur within 90 days of termination unless a shorter period is required by law.',
    ],
  },
  {
    title: '9. Governing Law',
    content: [
      'These Terms are governed by the laws of the State of California, United States.',
      'Any disputes shall be resolved through binding arbitration in San Francisco, CA.',
      'You waive any right to a jury trial in connection with disputes arising from these Terms.',
    ],
  },
  {
    title: '10. Contact Information',
    content: [
      'For questions about these Terms, contact us at: sales@thetaurus.ai',
      'Aashvi, 3rd Floor, Channasandra Main Road, Whitefield, Bangalore – 560066, India',
      'Phone: +91 63634 02404',
    ],
  },
];

export default function TermsAndConditionsPage() {
  return (
    <div className="min-h-screen bg-background font-sans pt-20">
      {/* Hero */}
      <section className="bg-background border-b border-white/10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-blue-900/30 text-blue-400 rounded-full text-sm font-bold mb-6 border border-blue-500/20">
            <FileText size={14} />
            Legal
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4 font-display">Terms & Conditions</h1>
          <p className="text-xl text-slate-400 max-w-2xl mx-auto leading-relaxed">
            Last updated: February 2026. Please read these terms carefully before using Taurus AI's services.
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
          {sections.map((sec, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.05 }}
              className="bg-card rounded-2xl border border-white/10 p-8 hover:border-blue-500/20 transition-all"
            >
              <h2 className="text-xl font-bold text-white mb-4">{sec.title}</h2>
              <ul className="space-y-3">
                {sec.content.map((item, i) => (
                  <li key={i} className="flex items-start gap-3 text-slate-400 leading-relaxed">
                    <span className="mt-2 w-1.5 h-1.5 rounded-full bg-blue-400 flex-shrink-0" />
                    {item}
                  </li>
                ))}
              </ul>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Bottom CTA */}
      <section className="bg-secondary py-12 text-center text-white">
        <div className="max-w-4xl mx-auto px-4">
          <p className="text-slate-300 mb-4">Have questions about our terms?</p>
          <Link to="/contact-us" className="inline-flex items-center gap-2 text-blue-400 hover:text-blue-300 font-semibold transition-colors">
            Contact Us <ChevronRight size={16} />
          </Link>
        </div>
      </section>
    </div>
  );
}
