import { useRef } from 'react';
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogDescription,
  DialogFooter
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Download, CheckCircle, AlertCircle, Share2, Printer } from 'lucide-react';
import { motion } from 'framer-motion';

interface SampleReportModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export default function SampleReportModal({ open, onOpenChange }: SampleReportModalProps) {
  const contentRef = useRef<HTMLDivElement>(null);

  const handleDownload = () => {
    // Basic text download simulation
    const reportText = `
Candidate Screening Report
--------------------------
Candidate: Sarah Jenkins
Role: Senior Frontend Engineer
Date: Oct 24, 2025
Overall Score: 88/100 (Strong Match)

Technical Skills: 9/10
Communication: 8.5/10
Problem Solving: 9/10

Key Insights:
- Strong understanding of React ecosystem and state management.
- Demonstrated excellent system design capabilities.
- Clear and concise communication style.

Recommendation: Proceed to Onsite Interview.
    `;
    
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'Sarah_Jenkins_Screening_Report.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl text-white">
            <Share2 className="w-5 h-5 text-primary" />
            Candidate Screening Report
          </DialogTitle>
          <DialogDescription className="text-slate-400">
            Generated by Taurus Hire AI • Oct 24, 2025
          </DialogDescription>
        </DialogHeader>

        {/* Report Content */}
        <div ref={contentRef} className="space-y-6 py-4">
          {/* Header Section */}
          <div className="flex items-start justify-between border-b pb-6">
            <div className="flex items-center gap-4">
              <div className="w-16 h-16 rounded-full bg-slate-100 flex items-center justify-center text-xl font-bold text-slate-600">
                SJ
              </div>
              <div>
                <h3 className="text-xl font-bold text-white">Sarah Jenkins</h3>
                <p className="text-slate-300">Applied for: Senior Frontend Engineer</p>
                <div className="flex items-center gap-2 mt-2">
                  <span className="px-2 py-1 bg-green-100 text-green-700 text-xs font-medium rounded-full border border-green-200">
                    Recommended
                  </span>
                  <span className="text-xs text-slate-400">ID: #TR-8842</span>
                </div>
              </div>
            </div>
            <div className="text-right">
              <div className="text-3xl font-bold text-primary">88<span className="text-lg text-slate-400 font-medium">/100</span></div>
              <p className="text-sm text-slate-400">Overall Match Score</p>
            </div>
          </div>

          {/* Scores Grid */}
          <div className="grid md:grid-cols-3 gap-4">
            <ReportCard title="Technical Skills" score={9.0} color="text-blue-600" bg="bg-blue-600" />
            <ReportCard title="Communication" score={8.5} color="text-purple-600" bg="bg-purple-600" />
            <ReportCard title="Problem Solving" score={9.0} color="text-amber-600" bg="bg-amber-600" />
          </div>

          {/* Detailed Analysis */}
          <div className="grid md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <h4 className="font-semibold text-white flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-green-500" />
                Key Strengths
              </h4>
              <ul className="space-y-2 text-sm text-slate-200">
                <li className="flex gap-2">
                  <span className="w-1 h-1 rounded-full bg-slate-400 mt-2 shrink-0" />
                  Exceptional grasp of React lifecycles and performance optimization techniques.
                </li>
                <li className="flex gap-2">
                  <span className="w-1 h-1 rounded-full bg-slate-400 mt-2 shrink-0" />
                  Structured approach to system design, considering scalability and edge cases.
                </li>
                <li className="flex gap-2">
                  <span className="w-1 h-1 rounded-full bg-slate-400 mt-2 shrink-0" />
                  Very articulate when explaining complex technical concepts.
                </li>
              </ul>
            </div>

            <div className="space-y-4">
              <h4 className="font-semibold text-white flex items-center gap-2">
                <AlertCircle className="w-4 h-4 text-amber-500" />
                Areas for Improvement
              </h4>
              <ul className="space-y-2 text-sm text-slate-200">
                <li className="flex gap-2">
                  <span className="w-1 h-1 rounded-full bg-slate-400 mt-2 shrink-0" />
                  Could get more familiar with GraphQL subscriptions.
                </li>
                <li className="flex gap-2">
                  <span className="w-1 h-1 rounded-full bg-slate-400 mt-2 shrink-0" />
                  Minor syntax improvement needed in error handling patterns.
                </li>
              </ul>
            </div>
          </div>

          {/* Automated Summary */}
          <div className="bg-slate-50 p-4 rounded-lg border">
            <h4 className="font-medium text-slate-900 mb-2">AI Summary</h4>
            <p className="text-sm text-slate-600 leading-relaxed">
              Sarah demonstrates a senior-level understanding of frontend technologies. She solved the algorithmic challenge efficiently (Time: O(n)) and explained her thought process clearly. Her communication skills are a strong asset for a collaborative team environment. Based on the technical assessment and behavioral responses, she is a <strong>Strong Match</strong> for the role.
            </p>
          </div>
        </div>

        <DialogFooter className="sm:justify-between gap-4 border-t pt-4">
          <div className="text-xs text-slate-400 flex items-center">
            * This is a sample report generated for demonstration.
          </div>
          <div className="flex gap-2">
            <Button variant="outline" onClick={handlePrint} className="gap-2">
              <Printer className="w-4 h-4" />
              Print
            </Button>
            <Button onClick={handleDownload} className="gap-2">
              <Download className="w-4 h-4" />
              Download Report
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function ReportCard({ title, score, color, bg }: { title: string, score: number, color: string, bg: string }) {
  return (
    <div className="p-4 rounded-lg border bg-card shadow-sm">
      <div className="text-sm text-slate-300 mb-1">{title}</div>
      <div className="flex items-end justify-between">
        <div className={`text-2xl font-bold ${color}`}>{score}</div>
        <div className="text-xs text-slate-400 mb-1">/ 10</div>
      </div>
      <div className="h-1.5 w-full bg-slate-100 rounded-full mt-2 overflow-hidden">
        <motion.div 
          initial={{ width: 0 }}
          animate={{ width: `${score * 10}%` }}
          transition={{ duration: 1, delay: 0.2 }}
          className={`h-full ${bg} rounded-full`} 
        />
      </div>
    </div>
  );
}
