// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kptqkzijsnbzzunlwixo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwdHFremlqc25ienp1bmx3aXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjE5MjIsImV4cCI6MjA3MTA5NzkyMn0.ihoKnNkAJInVPOE9ohoI1RcLUCzW00f-3RO1B_Z4O5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});